import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:material_symbols_icons/symbols.dart';

import '../theme/tt_colors.dart';
import '../theme/tt_tokens.dart';

/// "#NammaOoru · Made in Coimbatore" footer at the end of the passenger home sheet: a full-width band of
/// line art (the Big Temple, the Nilgiri train, a gopuram, a Bharatanatyam dancer, a farmer ploughing with
/// Kangayam bulls, an auto and a bike taxi) with the words over its empty top.
/// The art is generated by scripts/footer_art/build.py.
class HomeFooter extends StatelessWidget {
  const HomeFooter({super.key});

  static const asset = 'packages/tamiltaxi_ui/assets/illustrations/home_footer.svg';

  /// Width : height of the art (its SVG viewBox is 360 × 308).
  static const aspectRatio = 360 / 308;

  @override
  Widget build(BuildContext context) {
    final t = context.type;
    return Semantics(
      container: true,
      excludeSemantics: true,
      label: 'Namma Ooru. Made in Coimbatore',
      child: AspectRatio(
        aspectRatio: aspectRatio,
        child: Stack(
          fit: StackFit.expand,
          children: [
            SvgPicture.asset(asset, fit: BoxFit.cover),
            Padding(
              padding: const EdgeInsets.fromLTRB(20, 20, 20, 0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  FittedBox(
                    fit: BoxFit.scaleDown,
                    alignment: Alignment.centerLeft,
                    child: Text(
                      '#NammaOoru',
                      maxLines: 1,
                      style: t.display.copyWith(fontSize: 40, height: 1.2, color: TtColors.navy300),
                    ),
                  ),
                  const SizedBox(height: 4),
                  Row(
                    children: [
                      const Icon(Symbols.location_on_rounded, size: 18, fill: 1, color: TtColors.coral500),
                      const SizedBox(width: 4),
                      Flexible(
                        child: Text(
                          'Made in Coimbatore',
                          style: t.bodySmallMedium.copyWith(color: TtColors.navy700),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
